name = 'plevy26_lines'
license = 'MIT'
licenselink = 'https://github.com/picchono/CDJP'
description = 'Theme for the CDJP website'

version = "1.0.1"

# Taxonomy terms
tags = ['blog', 'tailwindcss', 'responsive', 'multilingual', 'dark', 'personal']
features = [
  "responsive",
  "dark mode",
  "table of contents",
  "katex",
  "tabler icons",
  "multilingual",
  "search",
]